name: 'Classic Discord Webhook'
description: 'This GitHub Action sends simple discord messages for your commits.'
branding:
  icon: activity
  color: gray-dark

inputs:
  id:
    description: The Discord Webhook ID
    required: true
  token:
    description: The Discord Webhook Token
    required: true
  repoName:
    description: Overrides default repo name
    required: false
  avatarUrl:
    description: The avatar URL for the webhook
    required: false
  hideCommitUrl:
    description: Hides the commit URL in the message
    required: false
  debug:
    description: Enables debug mode
    required: false

runs:
  using: 'node20'
  main: 'src/index.js'